### ISSUE TITLE
Error compiling the firmware in Arduino IDE

### ISSUE THREAD

**Issue by jamieharwood** [cleanflight/blackbox-firmware#1]
Hi,

I've copied the libraries to the correct folder but when I compile I get the error below. Any ideas what I'm doing wrong?

In file included from OpenLog_v3_Blackbox.ino:55:0:
/Users/jamie/Documents/Arduino/libraries/SerialPort/SerialPort.h: In member function 'size_t SerialPort<PortNumber, RxBufSize, TxBufSize>::write(const __FlashStringHelper_)':
/Users/jamie/Documents/Arduino/libraries/SerialPort/SerialPort.h:583:11: error: 'prog_char' does not name a type
     const prog_char_ p = (const prog_char*)s;
           ^
/Users/jamie/Documents/Arduino/libraries/SerialPort/SerialPort.h:584:25: error: 'p' was not declared in this scope
     size_t n = strlen_P(p);
                         ^
Error compiling.

**Comment by thenickdude** [comment]
Hm, which version of the Arduino IDE are you using? I'm using 1.0.6

**Comment by jamieharwood** [comment]
I was using 1.5.8 (I normally code for the Due), what a noob error!

**Comment by ohhorob** [comment]
The SerialPort library needs a small update to compile correctly.

in SerialPort.h, change `prog_char` to `char`

**Comment by thenickdude** [comment]
Looks like the current version of the SerialPort library we're including already has that change applied?
