### ISSUE TITLE
Can't Compile Blackbox Firmware

### ISSUE THREAD

**Issue by ghost** [cleanflight/blackbox-firmware#3]
Trying to update the Sparkfun OpenLog board but can't get past these errors.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
Arduino: 1.0.6 (Windows 7), Board: "Arduino Uno"
OpenLog_v3_Blackbox:58: error: expected constructor, destructor, or type conversion before '<' token
OpenLog_v3_Blackbox:108: error: 'Sd2Card' does not name a type
OpenLog_v3_Blackbox:109: error: 'SdVolume' does not name a type
OpenLog_v3_Blackbox:110: error: 'SdFile' does not name a type
OpenLog_v3_Blackbox.ino: In function 'void systemError(byte)':
OpenLog_v3_Blackbox:135: error: 'NewSerial' was not declared in this scope
OpenLog_v3_Blackbox.ino: In function 'void setup()':
OpenLog_v3_Blackbox:177: error: 'NewSerial' was not declared in this scope
OpenLog_v3_Blackbox:189: error: 'card' was not declared in this scope
OpenLog_v3_Blackbox:189: error: 'SPI_FULL_SPEED' was not declared in this scope
OpenLog_v3_Blackbox:191: error: 'volume' was not declared in this scope
OpenLog_v3_Blackbox:191: error: 'card' was not declared in this scope
OpenLog_v3_Blackbox:193: error: 'currentDirectory' was not declared in this scope
OpenLog_v3_Blackbox:194: error: 'volume' was not declared in this scope
OpenLog_v3_Blackbox.ino: In function 'char\* newlog()':
OpenLog_v3_Blackbox:223: error: 'SdFile' was not declared in this scope
OpenLog_v3_Blackbox:223: error: expected `;' before 'newFile'
OpenLog_v3_Blackbox:250: error: 'newFile' was not declared in this scope
OpenLog_v3_Blackbox:250: error: 'currentDirectory' was not declared in this scope
OpenLog_v3_Blackbox:251: error: 'O_CREAT' was not declared in this scope
OpenLog_v3_Blackbox:251: error: 'O_EXCL' was not declared in this scope
OpenLog_v3_Blackbox:251: error: 'O_WRITE' was not declared in this scope
OpenLog_v3_Blackbox:255: error: 'newFile' was not declared in this scope
OpenLog_v3_Blackbox:255: error: 'currentDirectory' was not declared in this scope
OpenLog_v3_Blackbox:255: error: 'O_READ' was not declared in this scope
OpenLog_v3_Blackbox:266: error: 'newFile' was not declared in this scope
OpenLog_v3_Blackbox.ino: In function 'void seqlog()':
OpenLog_v3_Blackbox:295: error: 'SdFile' was not declared in this scope
OpenLog_v3_Blackbox:295: error: expected`;' before 'seqFile'
OpenLog_v3_Blackbox:301: error: 'seqFile' was not declared in this scope
OpenLog_v3_Blackbox:301: error: 'currentDirectory' was not declared in this scope
OpenLog_v3_Blackbox:302: error: 'O_CREAT' was not declared in this scope
OpenLog_v3_Blackbox:302: error: 'O_WRITE' was not declared in this scope
OpenLog_v3_Blackbox:303: error: 'NewSerial' was not declared in this scope
OpenLog_v3_Blackbox:307: error: 'seqFile' was not declared in this scope
OpenLog_v3_Blackbox.ino: In function 'void append_file(char*)':
OpenLog_v3_Blackbox:317: error: 'SdFile' was not declared in this scope
OpenLog_v3_Blackbox:317: error: expected `;' before 'workingFile'
OpenLog_v3_Blackbox:322: error: 'workingFile' was not declared in this scope
OpenLog_v3_Blackbox:322: error: 'currentDirectory' was not declared in this scope
OpenLog_v3_Blackbox:322: error: 'O_CREAT' was not declared in this scope
OpenLog_v3_Blackbox:322: error: 'O_APPEND' was not declared in this scope
OpenLog_v3_Blackbox:322: error: 'O_WRITE' was not declared in this scope
OpenLog_v3_Blackbox:325: error: 'workingFile' was not declared in this scope
OpenLog_v3_Blackbox:331: error: 'NewSerial' was not declared in this scope
OpenLog_v3_Blackbox:348: error: 'workingFile' was not declared in this scope
OpenLog_v3_Blackbox:362: error: 'workingFile' was not declared in this scope

**Comment by thenickdude** [comment]
Those are the errors expected if the required libraries aren't installed into the right folder (or potentially if the Arduino IDE hasn't been restarted after installing them). (Details are in the readme if you need to double check)

**Comment by CradyCopter** [comment]
Thanks for the tip. I now have the libraries working -- I had followed the instructions to-the-letter which was a mistake. The folders that actually needed to be added were the subfolders 'SdFat' and 'SerialPort'. Selecting the top level folders wasn't enough. 
Anyway, now I'm getting the "avrdude: stk500_getsync(): not in sync: resp=0x00" error.

=(

**Comment by thenickdude** [comment]
I'm confused about how those directions could mean something else when followed to the letter, doesn't it explicitly say to copy those folders? 

Are you using a programmer or are you trying to upload using an FTDI cable? If FTDI, choose the option to upload rather than upload using programmer.

**Comment by CradyCopter** [comment]
Yeah. I'm using an Adafruit FTDI cable and I am using 'upload', thanks.
As for the libraries, and go ahead - follow the instructions on GitHub with no deviation and you'll get the same errors I did.
Arduino will not drill down past the folders SdFatBeta20120108 and SerialPortBeta20120106.  You must specifically select their SdFat and SerialPort subfolders.

**Comment by thenickdude** [comment]
Are we looking at the same repository?

```
You'll need to copy the required libraries to your Arduino 1.0.6 IDE's library path
in order to build this from source. Copy the libs/SdFatBeta20120108/SdFat and 
libs/SerialPortBeta20120106/SerialPort folders to your libraries folder directly 
(don't copy the outer folders "SdFatBeta20120108" or "SerialPortBeta20120106".)
```

Not only does it explicitly say to copy the SdFat and SerialPort folders, it explicitly says not to copy the outer SdFatBeta20120108 or SerialPortBeta20120106 folders. Or am I going insane?

Your error message looks like it's trying to upload using the avrdude programmer instead of trying to upload to an FTDI cable. I don't know why it would do that if you select the Upload option. Maybe verify that the correct serial port is selected in Tools->Serial Port?

**Comment by CradyCopter** [comment]
Got it.  I went back and looked at the specs for the Sparkfun board.  You can't connect it directly to an FTDI board -- you need to first swap the Tx and Rx.  They sell a crossover board for that purpose but fortunately I had some headers and patch leads.
Thanks for the help!

**Comment by thenickdude** [comment]
Yeah, it says that in the next paragraph! lol
