### ISSUE TITLE
Arduino Upload error

### ISSUE THREAD

**Issue by sniperxnl** [cleanflight/blackbox-firmware#6]
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x45
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x72
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x72
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0x6f
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x72
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0x20
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0x63
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x61
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0x72
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0x64

**Comment by timdonovanuk** [comment]
Same. This doesn't seem to work, neither is it clear how to actually just upload the precompiled hex file.

**Comment by Livewire85** [comment]
Im getting the same issue, anyone had any luck??

**Comment by InAmberClad** [comment]
Same issue here. Using [this](http://www.banggood.com/OpenLog-Serial-Data-Logger-9660bps-PPZ-Flight-Control-Record-FAT16-FAT32-MicroSD-Cards-p-993844.html) OpenLog board.

**Comment by grandars** [comment]
Check the wiring of your FTDI.

**Comment by Jahnkeanater** [comment]
Try resting the board right before its finished compiling. If the serial port is in use by the code you cant upload a sketch to it. Or use an FTDI programmer and connect the reset pin so the software can do this automatically. (If still having an issue, be sure to say what hardware you're using!)

**Comment by thenickdude** [comment]
Ensure your serial cable connects the DTR pin, it's required for the Arduino software to trigger a reset to enter bootloader mode.

**Comment by InAmberClad** [comment]
I've tried all these and still no luck. I have a feeling the board doesn't have the correct bootloader.

**Comment by AnthonyJQQ** [comment]
Make sure that you have Arduino UNO selected as your board and that you have TX and RX connected properly-  You cannot connect the Open Log directly to a FTDI Board.  You have to swap the Tx & Rx lines because they are backwards on the open-log.

**Comment by beb38138** [comment]
I'm having sync issues. I have tx to rx and so forth. I have verified my ftdi works by flashing minimosd. I have the correct folders in the library and the sketch compiles, but never completes

**Comment by jameswood** [comment]
I had the same problem as @sniperxnl 

It turns out I had to set `Board` to `Arduino Pro or Pro Mini`, instead of `Uno`, then the Arduino environment flashed it without a problem.

**Comment by edit21** [comment]
Same issue - same fix from Jameswood works just fine, ty!
